version: "3"
services:
  guacamole-frps:
    image: guacamole-frps
    build: ./frp/frps
    environment:
      - FRP_SERVER_PORT=15000
      - FRP_AUTH_TOKEN=*********
    ports: 
      - "15000:15000"

  guacamole-mysql:
    image: guacamole-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    build: ./mysql

  guacamole-guacd:
    image: guacd-chinese
    build: ./guacd
    depends_on:
      - guacamole-frps
    links:
      - guacamole-frps:frps

  guacamole-guacamole:
    image: guacamole/guacamole
    environment:
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=guacamole
    ports:
      - "8080:8080"
    depends_on:
      - guacamole-mysql
      - guacamole-frps
      - guacamol-guacd
    links:
      - guacamole-mysql:mysql
      - guacamole-frps:frps
      - guacamole-guacd:guacd

