version: "3"
services:
  frps:
    image: guacamole-frps
    build: ./frp/frps
    environment:
      - FRP_SERVER_PORT=15000
      - FRP_AUTH_TOKEN=*********
    ports: 
      - "15000:15000"

  guacd:
    image: guacd-chinese
    build: ./guacd
    depends_on:
      - frps
    links:
      - frps

  mysql:
    image: guacamole-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    build: ./mysql

  guacamole:
    image: guacamole/guacamole
    environment:
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=guacamole
      - GUACD_HOSTNAME=guacd
    ports:
      - "8080:8080"
    depends_on:
      - guacd
      - mysql
      - frps
    links:
      - guacd
      - mysql
      - frps