user = "frpc"

serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"

serverPOrt = "{{ .Envs.FRP_SERVER_PORT }}"

auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

[[proxies]]
name = "{{ .ENV.FRP_SERVICE_NAME}}"
type = "{{ .ENV.FRP_PROXY_TYPE }}"
localIp = "{{ .Envs.FRP_LOCAL_IP }}"
localPort = "{{ .Envs.FRP_LOCAL_PORT }}"
remotePort = "{{ .ENV.FRP_REMOTE_PORT }}"
